name: Deploy Medusa to AWS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Medusa Backend to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Stored in GitHub Secrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }} # Update this in GitHub Secrets
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG

      - name: Deploy to ECS
        run: |
          ecs-cli configure --cluster ${{ secrets.ECS_CLUSTER }} --default-launch-type FARGATE --region ${{ secrets.AWS_REGION }}
          ecs-cli compose --file docker-compose.yml service up --cluster-config ${{ secrets.ECS_CLUSTER_CONFIG }} --create-log-groups --force-deployment

